import { Books } from '../../interfaces/biblia.interface';

export const BOOKS: Books[] = [
    {
        book_number: 10,
        name: "Gênesis",
        testament: "old",
        group: 'Pentateuco',
        short_name: "Gn",
        long_name: "O Primeiro Livro de Moisés chamado Gênesis",
        resume: "Esse é o livro das origens, pois conta a origem do mundo, da humanidade e do povo hebreu. Os primeiros capítulos contam a origem da humanidade, desde os dias da criação até o dilúvio. A partir do capítulo 12, é contada a história dos três patriarcas dos hebreus: Abraão, Isaque e Jacó. A história termina com os filhos de Jacó no Egito, preparando a narrativa do livro de Êxodo.",
        book_color: "#ccccff",
        chapters: 50
    },
    {
        book_number: 20,
        name: "Êxodo",
        testament: "old",
        group: 'Pentateuco',
        short_name: "Êx",
        long_name: "O Segundo Livro de Moisés chamado Êxodo",
        resume: "Êxodo inicia-se com a história do nascimento de Moisés, passa pela sua fuga do Egito e formação de sua família em Midiã. Moisés é então chamado para retornar ao Egito pelo próprio Senhor, e recebe o poder de operar milagres e parte na missão de libertar os hebreus do Egito. Ao retornar ao Egito, confronta o faraó diversas vezes, alertando-o acerca da justiça de Deus. Após as dez pragas devastarem o povo e a terra, o faraó libera-os. Não muito tempo depois, o exército egípcio persegue os hebreus em fuga. Nesse momento, Moisés opera a abertura do mar para que o povo atravessasse em terra seca. Os hebreus peregrinam até o Monte Sinai, onde se estabelecem por um período. Nesse tempo, Moisés recebe a Lei de Deus, normais que deveriam guiar o povo de Deus.",
        book_color: "#ccccff",
        chapters: 40
    },
    {
        book_number: 30,
        name: "Levítico",
        testament: "old",
        group: 'Pentateuco',
        short_name: "Lv",
        long_name: "O Terceiro Livro de Moisés chamado Levítico",
        resume: "Levítico é o livro da pureza, pois ressalta a santidade e pureza que o povo de Deus deveria ter, de forma que reflita a pureza do próprio Deus. Nele estão contidos diversas leis sobre os sacerdotes, o tabernáculo e os procedimentos de pureza. Além disso, é encontrado também ensinos morais.",
        book_color: "#ccccff",
        chapters: 27
    },
    {
        book_number: 40,
        name: "Números",
        testament: "old",
        group: 'Pentateuco',
        short_name: "Nm",
        long_name: "O Quarto Livro de Moisés chamado Números",
        resume: "Números continua a jornada dos hebreus rumo a terra prometida. O livro recebe esse nome por começar fazendo contagens dentre o povo, especificamente daqueles que estão aptos a guerrear na conquista da terra. Nesse livro também são passados novas leis e instruções ao povo. Fica claro que o grande desafio é a obediência dos hebreus na missão de conquistar a terra, pois em determinado momento eles cogitam até mesmo voltar ao Egito.",
        book_color: "#ccccff",
        chapters: 36
    },
    {
        book_number: 50,
        name: "Deuteronômio",
        testament: "old",
        group: 'Pentateuco',
        short_name: "Dt",
        long_name: "O Quinto Livro de Moisés chamado Deuteronômio",
        resume: "Esse é o livro da repetição da Lei, pois muito tempo se passou desde que Deus deu a Lei em Êxodo. O povo hebreu estava prestes a conquistar a terra, por isso Moisés reforçou os mandamentos, tornando-os bem práticos. O livro termina fazendo a transição da liderança de Israel, de Moisés para Josué. Os últimos capítulos são marcados pelo cântico de Moisés e o relato de sua morte.",
        book_color: "#ccccff",
        chapters: 34
    },
    {
        book_number: 60,
        name: "Josué",
        testament: "old",
        group: 'Históricos',
        short_name: "Js",
        long_name: "O Livro de Josué",
        resume: "Josué é um livro de conteúdo militar, pois narra a conquista da terra prometida, Canaã, em todo o território. Entre diversos episódios de batalha, a conquista de Jericó e a paralisação do Sol e da Lua são os mais conhecidos. Após vencer diversos reis e exércitos, Josué realiza a distribuição das terras para cada tribo de Israel.",
        book_color: "#ffcc99",
        chapters: 24
    },
    {
        book_number: 70,
        name: "Juízes",
        testament: "old",
        group: 'Históricos',
        short_name: "Jz",
        long_name: "O Livro dos Juízes",
        resume: "Juízes acontece após a conquista da terra com Josué, mas antes do início da monarquia em Israel. Cada tribo agia de maneira independente, formando alianças ou desavenças. Como não havia um único líder sobre o povo, Deus levantava juízes periodicamente. Os juízes agiam como líderes militares e políticos, eram enviados por Deus para dar alívio ao povo, quando outra nação começava a prejudicá-los.",
        book_color: "#ffcc99",
        chapters: 21
    },
    {
        book_number: 80,
        name: "Rute",
        testament: "old",
        group: 'Históricos',
        short_name: "Rt",
        long_name: "O Livro de Rute",
        resume: "Rute é um livro calmo e tranquilo, se comparado com Juízes e Samuel. A história de Rute também se passa entre esses dois livros, com sua introdução a localizando na época dos juízes de Israel. Rute é a nora de Noemi, ela acompanha sua sogra quando todos os homens da família morrem. Ao invés de retornar à sua terra natal, como era direito, Rute decidiu permanecer ao lado de Noemi, estando decidida a lhe prover sustento. Rute se relaciona romanticamente com Boaz, e a partir disso a condição das duas é restaurada.",
        book_color: "#ffcc99",
        chapters: 4
    },
    {
        book_number: 90,
        name: "1 Samuel",
        testament: "old",
        group: 'Históricos',
        short_name: "1Sm",
        long_name: "O Primeiro Livro de Samuel",
        resume: "Esse livro conta a história de três pessoas: Samuel, o último juiz de Israel; Saul, o primeiro rei de Israel; e Davi, o maior rei de Israel. A história de Samuel começa com o relato de sua mãe, Ana, uma mulher de oração. Quando Deus concede um filho a Ana, ela consagra o menino Samuel ao Senhor, e ele cresce servindo com o sacerdote Eli. A história de Saul conta sua trajetória até o reinado, seus pecados e sua queda, principalmente sua perseguição contra Davi. Por sua vez, Davi foi encontrado por Samuel como o último filho de Jessé, é ungido como rei mas passa a ser perseguido por Saul. O último episódio desse livro é o suicídio de Saul.",
        book_color: "#ffcc99",
        chapters: 31
    },
    {
        book_number: 100,
        name: "2 Samuel",
        testament: "old",
        group: 'Históricos',
        short_name: "2Sm",
        long_name: "O Segundo Livro de Samuel",
        resume: "2 Samuel é a continuação da história de 1 Samuel, eles são, na verdade, o mesmo livro. No início do livro, Davi é reconhecido como rei perante o povo oficialmente, conquista Jerusalém e leva o Tabernáculo do Senhor para lá. Nesse livro, outro personagens marcante é o profeta Natã, que acompanha o reinado de Davi como conselheiro. Um episódio marcante é o adultério de Davi com Bate-Seba, a denúncia de Natã sobre o pecado de Davi e a morte do filho dessa união.",
        book_color: "#ffcc99",
        chapters: 24
    },
    {
        book_number: 110,
        name: "1 Reis",
        testament: "old",
        group: 'Históricos',
        short_name: "1Rs",
        long_name: "O Primeiro Livro dos Reis",
        resume: "Esse livro começa iniciando o reinado do filho de Davi, Salomão. Deus concede à ele toda sabedoria necessária para guiar Seu povo. Em seguida, constrói o Templo do Senhor. Após sua morte, é narrado a divisão do reino em dois, Norte e Sul, e juntamente com isso a sucessão de reis que se seguiu em cada região. Paralelo a isso, inicia-se o ministério do profeta Elias.",
        book_color: "#ffcc99",
        chapters: 22
    },
    {
        book_number: 120,
        name: "2 Reis",
        testament: "old",
        group: 'Históricos',
        short_name: "2Rs",
        long_name: "O Segundo Livro dos Reis",
        resume: "Essa é a continuação direta da história de 1 Reis. Após a morte do profeta Elias, Eliseu assume o protagonismo, realizando diversos milagres. A sucessão de reis em Israel e Judá continua, e é narrado a queda de Israel pelo império Assírio, e posteriormente a queda de Judá pela Babilônia.",
        book_color: "#ffcc99",
        chapters: 25
    },
    {
        book_number: 130,
        name: "1 Crônicas",
        testament: "old",
        group: 'Históricos',
        short_name: "1Cr",
        long_name: "O Primeiro Livro das Crônicas",
        resume: "Esse livro foi escrito após o Exílio babilônico, de forma a reforçar toda a história e trajetória dos judeus até aquele momento. Crônicas rememora os eventos acontecidos nos livros de Samuel e Reis. Após nove capítulos de genealogia das tribos, o suicídio de Saul e a vida de Davi são contadas novamente. 1 Crônicas se encerra com a coroação de Salomão.",
        book_color: "#ffcc99",
        chapters: 29
    },
    {
        book_number: 140,
        name: "2 Crônicas",
        testament: "old",
        group: 'Históricos',
        short_name: "2Cr",
        long_name: "O Segundo Livro das Crônicas",
        resume: "Continuando a recapitulação histórica do povo judeu, essa segunda parte das Crônicas inicia-se com os atos do rei Salomão, em especial a construção do templo. O livro avança para o racha que ocorre no reino, e segue acompanhando os reinados do Norte e do Sul, destacando a ênfase do coração deles em seguir ao Senhor ou à ídolos. Por fim, termina com a queda de Jerusalém pelos babilônicos.",
        book_color: "#ffcc99",
        chapters: 36
    },
    {
        book_number: 150,
        name: "Esdras",
        testament: "old",
        group: 'Históricos',
        short_name: "Ed",
        long_name: "O Livro de Esdras",
        resume: "Esdras se passa após a queda do império da Babilônia. Os judeus que estavam exilados, agora estavam sob o império persa, que era mais generoso com eles e permitiram que voltassem à sua terra sagrada. Nesse livro é narrado o retorno do povo à Jerusalém, a reconstrução do Altar, do Templo e de Jerusalém como cidade.",
        book_color: "#ffcc99",
        chapters: 10
    },
    {
        book_number: 160,
        name: "Neemias",
        testament: "old",
        group: 'Históricos',
        short_name: "Ne",
        long_name: "O Livro de Neemias",
        resume: "Neemias é muito similar à Esdras, mas com pontos de vista diferentes. Neemias também narra o retorno do povo judeu a terra prometida, com ênfase no trabalho braçal, como a reconstrução dos muros. Um grande destaque é a oposição de reis que ocupavam as regiões vizinhas.",
        book_color: "#ffcc99",
        chapters: 13
    },
    {
        book_number: 190,
        name: "Ester",
        testament: "old",
        group: 'Históricos',
        short_name: "Et",
        long_name: "O Livro de Ester",
        resume: "Essa história também se passa após o a queda da Babilônia, e durante o império persa. Ester é a protagonista da história, uma mulher judia que foi escolhida para ser a esposa do rei persa Xerxes. Graças à sua sabedoria e astúcia, o povo judeu foi salvo.",
        book_color: "#ffcc99",
        chapters: 10
    },
    {
        book_number: 220,
        name: "Jó",
        testament: "old",
        group: 'Poéticos',
        short_name: "Jó",
        long_name: "O Livro de Jó",
        resume: "Jó é um livro de sabedoria. Seus primeiros e últimos capítulos são em formato de narrativa, mas todo seu miolo é formado por debates entre Jó e seus amigos. Esses debates contém muita metáfora, poesia e figuras daquela época e região. Dessa forma, são muito profundas e significativas. Nem tudo que é dito nesses diálogos são verdades absolutas, uma vez que o próprio Deus ao fim da narrativa condena e refuta algumas coisas. O elemento mais marcante do livro é a ação de Satanás no mundo estar sujeita à autorização de Deus.",
        book_color: "#66ff99",
        chapters: 42
    },
    {
        book_number: 230,
        name: "Salmos",
        testament: "old",
        group: 'Poéticos',
        short_name: "Sl",
        long_name: "O Livro dos Salmos",
        resume: "O livro de canções de Israel, formado por diversos autores em diversos períodos de tempo. O principal autor é Davi, o rei de Israel, que além de grande guerreiro, era músico e hábil em composição. Há quem diga que salmos é uma anatomia do coração humano, pois neles estão descritos todo tipo de sentimento que uma pessoa pode sentir, de maneira bela e poderosa. Salmos é dividido em 5 partes (também chamados de 5 livros).",
        book_color: "#66ff99",
        chapters: 150
    },
    {
        book_number: 240,
        name: "Salomão",
        testament: "old",
        group: 'Poéticos',
        short_name: "Pv",
        long_name: "Provérbios de Salomão",
        resume: "Provérbios é uma forma de sabedoria, são várias frases e ditados que contém ensinamentos para a vida. Seu conteúdo é extremamente prático e foca numa vida vivida com prudência e temor ao Senhor.",
        book_color: "#66ff99",
        chapters: 31
    },
    {
        book_number: 250,
        name: "Eclesiastes",
        testament: "old",
        group: 'Poéticos',
        short_name: "Ec",
        long_name: "Livro do Eclesiastes",
        resume: "Esse é o livro de reflexões e meditações mais profundas do rei Salomão. Seu tom é pessimista e causa estranheza aos seus leitores atuais. Eclesiastes não tem conclusões cristãs, mas suas ideias podem ser complementadas com as visões de eternidade que Jesus fornece.",
        book_color: "#66ff99",
        chapters: 12
    },
    {
        book_number: 260,
        name: "Cânticos",
        testament: "old",
        group: 'Poéticos',
        short_name: "Ct",
        long_name: "Cântico dos Cânticos de Salomão",
        resume: "Ou Cantares de Salomão, uma poesia musical feita pelo rei Salomão dedicada à sua amada Sulamita. O conteúdo desse livro é romântico e contém metáforas que apontam para uma vida de casado. Muitos interpretam a relação Salomão/Sulamita como uma metáfora em si para Cristo e a Igreja.",
        book_color: "#66ff99",
        chapters: 8
    },
    {
        book_number: 290,
        name: "Isaías",
        testament: "old",
        group: 'Profetas Maiores',
        short_name: "Is",
        long_name: "Isaías",
        resume: "Isaías é um dos livros chamados de \"profetas maiores\", sua relevância é muito grande, sendo o profeta que mais anunciou a vinda do Messias. Sua visão do salvador é a do 'servo sofredor', alguém que tomaria as dores das pessoas sobre si.",
        book_color: "#ff9fb4",
        chapters: 66
    },
    {
        book_number: 300,
        name: "Jeremias",
        testament: "old",
        group: 'Profetas Maiores',
        short_name: "Jr",
        long_name: "Jeremias",
        resume: "Jeremias também é um profeta maior, sua carreira inicia-se quando os judeus ainda estavam em Judá. Sua vida é marcada por anunciar o juízo de Deus, enquanto ninguém lhe dava ouvidos. Viveu para ver a conquista da Babilônia sobre Jerusalém, como castigo divino pela falta de arrependimento do povo.",
        book_color: "#ff9fb4",
        chapters: 52
    },
    {
        book_number: 310,
        name: "Lamentações",
        testament: "old",
        group: 'Profetas Maiores',
        short_name: "Lm",
        long_name: "Lamentações de Jeremias",
        resume: "Esse é o livro mais negativo e até mesmo triste de toda a Bíblia. Em face da destruição de Jerusalém pela Babilônia, o profeta Jeremias lamenta profundamente cada detalhe dessa derrota.",
        book_color: "#ff9fb4",
        chapters: 5
    },
    {
        book_number: 330,
        name: "Ezequiel",
        testament: "old",
        group: 'Profetas Maiores',
        short_name: "Ez",
        long_name: "Ezequiel",
        resume: "Ezequiel é outro dos profetas maiores, seu conteúdo é denso e muitas vezes confuso, porque Ezequiel é o profeta que mais tem visões sobrenaturais, sendo de difícil entendimento. Ezequiel profetizou quando Judá ainda estava de pé, mas em eminente destruição de acordo com suas predições. Ezequiel condenou fortemente a corrupção de profetas, sacerdotes e outras elites de Jerusalém.",
        book_color: "#ff9fb4",
        chapters: 48
    },
    {
        book_number: 340,
        name: "Daniel",
        testament: "old",
        group: 'Profetas Maiores',
        short_name: "Dn",
        long_name: "Daniel",
        resume: "Daniel e seus três amigos, fizeram parte do primeiro grupo de judeus exilados na Babilônia. Daniel foi um jovem confiante em Deus, que não aceitou adorar outros deuses. Além disso, foi abençoado por Deus com a capacidade de interpretar sonhos, o que lhe elevou para próximo do rei da Babilônia, Nabucodonosor, que lhe concedeu muitas vantagens.",
        book_color: "#ff9fb4",
        chapters: 12
    },
    {
        book_number: 350,
        name: "Oseias",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Os",
        long_name: "Oseias",
        resume: "Oséias é famoso por ser o profeta que Deus mandou se casar com uma prostituta. Esse episódio acontece porque Deus quis encenar a relação do povo com o próprio Senhor. Em outras palavras, Israel estava se prostituindo com outros deuses e líderes, ao invés de serem fieis a Deus.",
        book_color: "#ffff99",
        chapters: 14
    },
    {
        book_number: 360,
        name: "Joel",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Jl",
        long_name: "Joel",
        resume: "Joel anuncia e faz menção à uma praga de gafanhotos que viria sobre Israel como forma de juízo de Deus. Diante disso, Joel prega o arrependimento para Israel.",
        book_color: "#ffff99",
        chapters: 3
    },
    {
        book_number: 370,
        name: "Amós",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Am",
        long_name: "Amós",
        resume: "Amós é um livro em que a justiça divina em relação às injustiças da terra está no centro das questões. Esse profeta denuncia a corrupção em Israel, corrupção dos líderes, sacerdotes e outros profetas.",
        book_color: "#ffff99",
        chapters: 9
    },
    {
        book_number: 380,
        name: "Obadias",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Ob",
        long_name: "Obadias",
        resume: "Esse é um livro bem curto, de apenas um capítulo. O grande alvo de Deus, através da boca de Obadia, é Edom, por ter se satisfeito com a destruição de Jerusalém.",
        book_color: "#ffff99",
        chapters: 1
    },
    {
        book_number: 390,
        name: "Jonas",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Jn",
        long_name: "Jonas",
        resume: "Esse é um um pouco diferente dos demais livros proféticos, porque contém bastante narrativa. Jonas foi chamado por Deus para pregar o arrependimento à uma nação inimiga de Israel, sanguinária e pecaminosa. Por todas esses elementos, o profeta se recusou a seguir o chamado de Deus e fugiu para a direção oposta. Em face disso, Deus intervém, fazendo com que um grande peixe engula Jonas por três dias, fazendo com que ele se arrependa e vá finalmente pregar o arrependimento àquela nação.",
        book_color: "#ffff99",
        chapters: 4
    },
    {
        book_number: 400,
        name: "Miqueias",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Mq",
        long_name: "Miqueias",
        resume: "Miquéias prega contra Israel e Judá, sua mensagem intercala condenação e salvação e prediz a queda de Israel e de Jerusalém. Uma das passagens mais famosas desse profeta é a declaração de que de Belém sairia um governante.",
        book_color: "#ffff99",
        chapters: 7
    },
    {
        book_number: 410,
        name: "Naum",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Na",
        long_name: "Naum",
        resume: "Esse profeta prega contra Nínive, uma nação estrangeira conhecida por sua violência. Por esse motivo, Naum se distingue dos demais profetas. Muitos, principalmente os maiores, criticavam nações estrangeiras, mas não como a crítica principal, e dessa maneira é que Naum se destaca, já que seu principal alvo é estrangeiro.",
        book_color: "#ffff99",
        chapters: 3
    },
    {
        book_number: 420,
        name: "Habacuque",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Hc",
        long_name: "Habacuque",
        resume: "Diante da invasão babilônica contra Judá, Habacuque argumenta com Deus sobre a maldade do mundo. Num belo diálogo entre o profeta e o Senhor, a conclusão de que os maus receberão condenação e os bons justiça conclui o livro.",
        book_color: "#ffff99",
        chapters: 3
    },
    {
        book_number: 430,
        name: "Sofonias",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Sf",
        long_name: "Sofonias",
        resume: "De todos os profetas, Sofonias é o que mais fala sobre o Dia do Senhor, o dia em que Deus jugará a terra e todos seus habitantes. Justiça será feita ao justo e castigo será dado aos maus.",
        book_color: "#ffff99",
        chapters: 3
    },
    {
        book_number: 440,
        name: "Ageu",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Ag",
        long_name: "Ageu",
        resume: "O primeiro profeta a falar após o exílio da Babilônia, Ageu incentiva o povo a retomar e persistir na reconstrução do Templo, destruído na invasão dos babilônicos.",
        book_color: "#ffff99",
        chapters: 2
    },
    {
        book_number: 450,
        name: "Zacarias",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Zc",
        long_name: "Zacarias",
        resume: "Zacarias profetizou no tempo em que os judeus puderam retornar à terra prometida. Esse profeta é o mais apocaliptico, ou seja, é o que mais aponta para o fim do mundo e a nova criação de Deus.",
        book_color: "#ffff99",
        chapters: 14
    },
    {
        book_number: 460,
        name: "Malaquias",
        testament: "old",
        group: 'Profetas Menores',
        short_name: "Ml",
        long_name: "Malaquias",
        resume: "Esse profeta viveu após os judeus retornarem à Jerusalém. Suas palavras refletem a pureza espiritual causada por Esdras e Neemias, dessa forma o profeta denuncia casamentos proibidos, problemas com os sacerdotes e da adoração vazia.",
        book_color: "#ffff99",
        chapters: 4
    },
    {
        book_number: 470,
        name: "Mateus",
        testament: "new",
        group: 'Evangelhos',
        short_name: "Mt",
        long_name: "O Evangelho segundo Mateus",
        resume: "O Evangelho segundo Mateus, conta a vida e ministério de Jesus, contando seus milagres e ensino. O maior diferencial de Mateus são os cinco grandes discursos de Jesus que estão distribuídos através do livro.",
        book_color: "#ff6600",
        chapters: 28
    },
    {
        book_number: 480,
        name: "Marcos",
        testament: "new",
        group: 'Evangelhos',
        short_name: "Mc",
        long_name: "O Evangelho segundo Marcos",
        resume: "O Evangelho segundo Marcos, também conta a vida e ministério de Jesus. O menor dos quatro evangelhos, não relata o nascimento de Jesus e tem uma ênfase muito forte nas ações práticas de Cristo, além de dedicar uma parte grande de seu conteúdo à semana da paixão.",
        book_color: "#ff6600",
        chapters: 16
    },
    {
        book_number: 490,
        name: "Lucas",
        testament: "new",
        group: 'Evangelhos',
        short_name: "Lc",
        long_name: "O Evangelho segundo Lucas",
        resume: "O Evangelho segundo Lucas, conta a vida e ministério de Jesus em mais detalhes. Lucas era um historiador, e através de suas pesquisas conseguiu informações preciosas sobre o nascimento e infância de Jesus. Por ser historiador, também é o evangelho que segue melhor a ordem cronológica dos eventos.",
        book_color: "#ff6600",
        chapters: 24
    },
    {
        book_number: 500,
        name: "João",
        testament: "new",
        group: 'Evangelhos',
        short_name: "Jo",
        long_name: "O Evangelho segundo João",
        resume: "O Evangelho segundo João, é o mais diferente dos quatro evangelhos, até porque foi escrito depois dos outros três. João conta histórias inéditas da vida e ministério de Jesus, com detalhes e informações que somente alguém que era muito próximo poderia contar.",
        book_color: "#ff6600",
        chapters: 21
    },
    {
        book_number: 510,
        name: "Atos",
        testament: "new",
        group: 'Histórico',
        short_name: "At",
        long_name: "Atos dos Apóstolos",
        resume: "Segundo livro de Lucas, é na verdade uma continuação do Evangelho após a ascensão de Jesus. O foco da história aqui é o desenvolvimento da igreja primitiva, como ela se expandiu e como superou suas dificuldades. Os dois principais protagonistas do livro são o apóstolo Pedro e Paulo.",
        book_color: "#00ffff",
        chapters: 28
    },
    {
        book_number: 520,
        name: "Romanos",
        testament: "new",
        group: 'Epístolas',
        short_name: "Rm",
        long_name: "Epístola de Paulo aos Romanos",
        resume: "Carta de Paulo à igreja de Roma. Uma das cartas mais importantes da história da igreja, Paulo desenvolve toda sua teologia nela, desde a universalidade do pecado até a obra de salvação de Jesus Cristo. A partir do capítulo doze, Paulo escreve muitas instruções práticas.",
        book_color: "#ffff00",
        chapters: 16
    },
    {
        book_number: 530,
        name: "1 Coríntios",
        testament: "new",
        group: 'Epístolas',
        short_name: "1Co",
        long_name: "Primeira Epístola de Paulo aos Coríntios",
        resume: "Primeira carta à igreja de Corinto. Nessa carta, destaca-se o tom revoltado do apóstolo Paulo, pois era uma igreja que estava dividida e cheia de pecados. Paulo tenta tratar esses problemas à distância e ensiná-los a mentalidade correta. Nessa carta encontra-se o famoso texto do amor cristão.",
        book_color: "#ffff00",
        chapters: 16
    },
    {
        book_number: 540,
        name: "2 Coríntios",
        testament: "new",
        group: 'Epístolas',
        short_name: "2Co",
        long_name: "Segunda Epístola de Paulo aos Coríntios",
        resume: "Segunda carta aos coríntios, aqui Paulo ressalta seus sofrimentos como apóstolo e a habitação celestial. Além disso, incentiva a igreja a colaborarem financeiramente na ajuda à igreja da Judéia.",
        book_color: "#ffff00",
        chapters: 13
    },
    {
        book_number: 550,
        name: "Gálatas",
        testament: "new",
        group: 'Epístolas',
        short_name: "Gl",
        long_name: "Epístola de Paulo aos Gálatas",
        resume: "Carta de Paulo à igreja da Galácia. É uma carta marcada pela indignação do apóstolo pela disposição dessa igreja de abandonar o evangelho verdadeiro em prol de um evangelho falso e legalista. Nessa carta a luta do Espírito contra a carne e os frutos do Espírito são bem conhecidos.",
        book_color: "#ffff00",
        chapters: 6
    },
    {
        book_number: 560,
        name: "Efésios",
        testament: "new",
        group: 'Epístolas',
        short_name: "Ef",
        long_name: "Epístola de Paulo aos Efésios",
        resume: "Uma carta de Paulo aos irmãos de Éfeso. Esse escrito é com certeza uma carta, mas possui elementos de tratado teológico, por não envolver problemas locais específicos, mas desenvolve muita teologia, trabalhando conceito atrás de conceito. A ética da família cristã e a armadura de Deus são elementos bem conhecidos dessa carta.",
        book_color: "#ffff00",
        chapters: 6
    },
    {
        book_number: 570,
        name: "Filipenses",
        testament: "new",
        group: 'Epístolas',
        short_name: "Fp",
        long_name: "Epístola de Paulo aos Filipenses",
        resume: "Carta do apóstolo Paulo, conhecida como a 'carta da felicidade', porque o autor estava muito contente com o desempenho dessa igreja na fé em Jesus. A fé desses irmãos estava sendo conhecida em diversas regiões, o que alegrava o apóstolo. Um elemento muito conhecido dessa carta é a famosa descrição da humilhação de Jesus, por abandonar a forma de Deus e assumir forma de homem.",
        book_color: "#ffff00",
        chapters: 4
    },
    {
        book_number: 580,
        name: "Colossenses",
        testament: "new",
        group: 'Epístolas',
        short_name: "Cl",
        long_name: "Epístola de Paulo aos Colossenses",
        resume: "Carta de Paulo aos irmãos de Colossos. Nessa breve carta, o apóstolo conta os motivos de alegria que encontra nessa igreja, registra um louvor à supremacia de Cristo e instrui eles contra o legalismo.",
        book_color: "#ffff00",
        chapters: 4
    },
    {
        book_number: 590,
        name: "1 Tessalonicenses",
        testament: "new",
        group: 'Epístolas',
        short_name: "1Ts",
        long_name: "Primeira Epístola de Paulo aos Tessalonicenses",
        resume: "Uma carta curta, e provavelmente uma das primeiras do apóstolo Paulo. Ela incentiva os irmãos de Tessalônica a persistirem na caminhada cristã com excelência. O conteúdo mais marcante da carta é a descrição que Paulo faz do retorno de Jesus e nosso encontro com ele nos ares.",
        book_color: "#ffff00",
        chapters: 5
    },
    {
        book_number: 600,
        name: "2 Tessalonicenses",
        testament: "new",
        group: 'Epístolas',
        short_name: "2Ts",
        long_name: "Segunda Epístola de Paulo aos Tessalonicenses",
        resume: "Nessa pequena carta de respostas às necessidades da igreja de Tessalônica, Paulo adverte sobre o fim dos tempos e dá descrições acerca do anti-Cristo. Diante das dificuldades, o apóstolo também incentiva a perseverança dos irmãos.",
        book_color: "#ffff00",
        chapters: 3
    },
    {
        book_number: 610,
        name: "1 Timóteo",
        testament: "new",
        group: 'Epístolas',
        short_name: "1Tm",
        long_name: "Primeira Epístola de Paulo a Timóteo",
        resume: "Essa é uma carta pessoal entre Paulo e Timóteo, seu discípulo. Nessa carta encontram-se instruções valiosas acerca dos ofícios cristãos (pastor e diácono), com rigorosas exigências morais, de forma que o servo de Deus seja exemplar.",
        book_color: "#ffff00",
        chapters: 6
    },
    {
        book_number: 620,
        name: "2 Timóteo",
        testament: "new",
        group: 'Epístolas',
        short_name: "2Tm",
        long_name: "Segunda Epístola de Paulo a Timóteo",
        resume: "Segunda carta de Paulo ao seu discípulo. Agora já tem face da morte, Paulo incentiva seu pupilo a prosseguir firmemente na caminhada cristã e no serviço à Deus de maneira fiel. Conclui contente, sabendo que combateu o combate da fé",
        book_color: "#ffff00",
        chapters: 4
    },
    {
        book_number: 630,
        name: "Tito",
        testament: "new",
        group: 'Epístolas',
        short_name: "Tt",
        long_name: "Epístola de Paulo a Tito",
        resume: "Uma carta pessoal de Paulo à Tito, um colega e colaborador da fé. Nessa carta, Paulo dá instruções acerca dos ofícios cristãos (pastor e diácono).",
        book_color: "#ffff00",
        chapters: 3
    },
    {
        book_number: 640,
        name: "Filemom",
        testament: "new",
        group: 'Epístolas',
        short_name: "Fm",
        long_name: "Epístola de Paulo a Filemom",
        resume: "Nessa pequena carta, Paulo argumenta em favor de Onésimo, um escravo cristão que fugiu de seu senhor.",
        book_color: "#ffff00",
        chapters: 1
    },
    {
        book_number: 650,
        name: "Hebreus",
        testament: "new",
        group: 'Epístolas',
        short_name: "Hb",
        long_name: "Epístola aos Hebreus",
        resume: "Uma longa e complexa carta, a autoria de hebreus é desconhecida. Nessa carta, encontramos um grande tratado teológico, que desenvolve as ideias acerca de Jesus Cristo e seu lugar diante de Deus. Por fim, a carta incentiva que os irmãos continuem firmes na fé.",
        book_color: "#ffff00",
        chapters: 13
    },
    {
        book_number: 660,
        name: "Tiago",
        testament: "new",
        group: 'Epístolas',
        short_name: "Tg",
        long_name: "Epístola de Tiago",
        resume: "Escrita por Tiago, o meio irmão de Jesus, filho de José e Maria. Tiago se tornou um dos líderes da igreja de Jerusalém, poucos anos após a ascensão de Jesus. Essa carta contém um conteúdo muito prático, se assemelhando aos livros de sabedoria do Antigo Testamento. Muitos versos são bem conhecidos, mas um que se destaca é a ênfase do autor em praticar aquilo que se ouve.",
        book_color: "#00ff00",
        chapters: 5
    },
    {
        book_number: 670,
        name: "1 Pedro",
        testament: "new",
        group: 'Epístolas',
        short_name: "1Pe",
        long_name: "Primeira Epístola de Pedro",
        resume: "Escrita pelo apóstolo Pedro, essa carta contém uma voz pastoral, Pedro está cuidando do rebanho do Senhor. Ele incentiva a santidade, um bom comportamento civil dos cristãos, além dos valores cristãos no lar e na sociedade.",
        book_color: "#00ff00",
        chapters: 5
    },
    {
        book_number: 680,
        name: "2 Pedro",
        testament: "new",
        group: 'Epístolas',
        short_name: "2Pe",
        long_name: "Segunda Epístola de Pedro",
        resume: "Diante da perseguição que os cristãos estavam sofrendo, Pedro adverte seus leitores sobre os falsos ensinos que estavam sendo propagados no meio da igreja.",
        book_color: "#00ff00",
        chapters: 3
    },
    {
        book_number: 690,
        name: "1 João",
        testament: "new",
        group: 'Epístolas',
        short_name: "1Jo",
        long_name: "Primeira Epístola de João",
        resume: "Essa é conhecida como a carta do amor, pois o amor é a chave para todos os relacionamentos (entre Deus e os Homens, os Homens e Deus e entre os Homens).",
        book_color: "#00ff00",
        chapters: 5
    },
    {
        book_number: 700,
        name: "2 João",
        testament: "new",
        group: 'Epístolas',
        short_name: "2Jo",
        long_name: "Segunda Epístola de João",
        resume: "Uma carta curta e bem pessoal, João incentiva o amor cristão e adverte contra os falsos mestres.",
        book_color: "#00ff00",
        chapters: 1
    },
    {
        book_number: 710,
        name: "3 João",
        testament: "new",
        group: 'Epístolas',
        short_name: "3Jo",
        long_name: "Terceira Epístola de João",
        resume: "Uma carta curta e pessoal de João, destinada à Gaio. O valor dessa carta se encontra na qualidade do relacionamento de João com seu amigo.",
        book_color: "#00ff00",
        chapters: 1
    },
    {
        book_number: 720,
        name: "Judas",
        testament: "new",
        group: 'Epístolas',
        short_name: "Jd",
        long_name: "Epístola de Judas",
        resume: "Uma pequena carta escrita por Judas, meio irmão de Jesus Cristo. Essa carta contém uma forte exortação contra os falsos mestres que ameaçam a igreja.",
        book_color: "#00ff00",
        chapters: 1
    },
    {
        book_number: 730,
        name: "Apocalipse",
        testament: "new",
        group: 'Revelação',
        short_name: "Ap",
        long_name: "Apocalipse de João",
        resume: "Apocalipse também é uma carta, contando sobre uma revelação de como será o fim do mundo. Apocalipse contém diversas visões e revelações sobre o futuro, utiliza-se de muitas imagens e faz diversas críticas ao contexto que ela foi escrita. Esses fatores tornam a tarefa de interpretá-la bem difícil, o que exige bastante dedicação.",
        book_color: "#ff7c80",
        chapters: 22
    }
]